=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/model_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
    "type": "object",
    "required": [
        "name",
        "standby_power",
        "measure_method",
        "measure_device",
        "calculation_strategy"
    ],
    "properties": {
        "name": {
            "type": "string",
            "description": "The full name"
        },
        "standby_power": {
            "type": "number",
            "minimum": 0.05,
            "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
        },
        "standby_power_on": {
            "type": "number",
            "minimum": 0.05,
            "description": "Power draw when the device is turned on."
        },
        "calculation_strategy": {
            "type": "string",
            "enum": [
                "lut",
                "linear",
                "fixed"
            ],
            "description": "Supported calculation modes"
        },
        "measure_method": {
            "type": "string",
            "enum": [
                "manual",
                "script"
            ],
            "description": "How the device was measured"
        },
        "measure_device": {
            "type": "string",
            "description": "Device which was used to measure"
        },
        "measure_description": {
            "type": "string",
            "description": "Add more information about how you measured the device or any remarks"
        },
        "measure_settings": {
            "type": "object",
            "description": "Settings used for measure script"
        },
        "linked_lut": {
            "type": "string",
            "description": "Use LUT data files from another model"
        },
        "device_type": {
            "type": "string",
            "enum": [
                "light",
                "smart_switch",
                "smart_speaker"
            ],
            "description": "Type of device"
        },
        "calculation_enabled_condition": {
            "type": "string",
            "description": "Template which can be evaluated."
        },
        "aliases": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Aliases for this model"
        },
        "linear_config": {
            "type": "object",
            "description": "Configuration for linear calculation mode",
            "properties": {
                "min_power": {
                    "type": "number"
                },
                "max_power": {
                    "type": "number"
                },
                "calibrate": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "fixed_config": {
            "type": "object",
            "description": "Configuration for fixed calculation mode",
            "properties": {
                "power": {
                    "type": "number"
                },
                "states_power": {
                    "type": "object",
                    "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
                    "properties": {
                        "idle": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "playing": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "paused": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "off": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "unavailable": {
                            "type": [
                                "number",
                                "string"
                            ]
                        }
                    },
                    "additionalProperties": {
                        "type": [
                            "number",
                            "string"
                        ]
                    }
                }
            }
        },
        "config_flow_discovery_remarks": {
            "type": "string",
            "description": "Some remarks to show in the GUI config flow on first step of discovery"
        },
        "sensor_config": {
            "type": "object",
            "description": "Sensor configuration options. See the README"
        },
        "sub_profile_select": {
            "type": "object",
            "description": "Configuration to automatically select a sub profile",
            "required": [
                "default",
                "matchers"
            ],
            "properties": {
                "default": {
                    "type": "string",
                    "description": "Default profile to select when non of the matchers apply"
                },
                "matchers": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "enum": [
                                    "attribute",
                                    "entity_id",
                                    "entity_state"
                                ]
                            },
                            "attribute": {
                                "type": "string"
                            },
                            "map": {
                                "type": "object"
                            },
                            "pattern": {
                                "type": "string"
                            },
                            "profile": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "description": "List of matchers which will be checked"
                }
            }
        }
    }
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/tuya/TS011F/model.json
{
	"measure_description": "Measured manually",
	"measure_method": "manual",
	"measure_device": "PeakTech P 4250 (1 mV/10 mA) with VOLTCRAFT VC270",
	"name": "Smart plug (with power monitoring)",
	"standby_power": 0.13,
	"sensor_config": {
		"power_sensor_naming": "{} Device Power",
		"energy_sensor_naming": "{} Device Energy"
  	},
	"device_type": "smart_switch",
	"calculation_strategy": "fixed",
	"fixed_config": {
		"power": 0.39
	},
	"aliases": [
		"TS011F_plug_1",
		"TS011F_plug_3",
		"TS011F"
	]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/signify/LCF002/model.json
{
   "name":"Hue Calla Outdoor Pedestal",
   "standby_power":0.4,
   "calculation_strategy": "lut",
   "measure_device":"Gosund SP111 on Tasmota 9.5.0",
   "measure_description":"Measure Script for Tasmota",
   "measure_method":"script",
   "aliases": [
        "1742030P7",
        "8718696167991",
        "LCF001"
    ]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/signify/LWB006/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly, Plus1PM",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "master"
    },
    "aliases": [
        "9290011370"
    ],
    "name": "Hue white A60 bulb E27/B22",
    "standby_power": 0.4
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/signify/LTW011/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "SONOFF S31",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v1.3.13:docker"
    },
    "name": "Hue White Ambiance BR30 680lm WW Bulb",
    "standby_power": 0.25
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/signify/929003045001/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly 1PM",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "master"
    },
    "name": "Hue White Ambiance Milliskin",
    "standby_power": 0.3,
    "aliases": [
        "929003045001_01",
        "929003045001_02",
        "929003045001_03"
    ]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/innr/AE 280 C/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Sonoff S31",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 3,
        "SLEEP_TIME": 15,
        "VERSION": "v0.19.16:docker"
    },
    "name": "Smart Bulb Color E27",
    "standby_power": 0.11,
    "calculation_strategy": "lut"
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/genio/I004544/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Tapo P110",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "master"
    },
    "name": "Mirabella 9W 750Lm RGBW Downlight",
    "standby_power": 0.24
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/innr/RB 148 T/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Nous A1T",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v1.3.1:docker"
    },
    "name": "RB 148 T - E14 candle tuneable white",
    "standby_power": 0.48
}
