=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/model_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
    "type": "object",
    "required": [
        "name",
        "standby_power",
        "measure_method",
        "measure_device",
        "calculation_strategy"
    ],
    "properties": {
        "name": {
            "type": "string",
            "description": "The full name"
        },
        "standby_power": {
            "type": "number",
            "minimum": 0.05,
            "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
        },
        "standby_power_on": {
            "type": "number",
            "minimum": 0.05,
            "description": "Power draw when the device is turned on."
        },
        "calculation_strategy": {
            "type": "string",
            "enum": [
                "lut",
                "linear",
                "fixed"
            ],
            "description": "Supported calculation modes"
        },
        "measure_method": {
            "type": "string",
            "enum": [
                "manual",
                "script"
            ],
            "description": "How the device was measured"
        },
        "measure_device": {
            "type": "string",
            "description": "Device which was used to measure"
        },
        "measure_description": {
            "type": "string",
            "description": "Add more information about how you measured the device or any remarks"
        },
        "measure_settings": {
            "type": "object",
            "description": "Settings used for measure script"
        },
        "linked_lut": {
            "type": "string",
            "description": "Use LUT data files from another model"
        },
        "device_type": {
            "type": "string",
            "enum": [
                "light",
                "smart_switch",
                "smart_speaker"
            ],
            "description": "Type of device"
        },
        "calculation_enabled_condition": {
            "type": "string",
            "description": "Template which can be evaluated."
        },
        "aliases": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Aliases for this model"
        },
        "linear_config": {
            "type": "object",
            "description": "Configuration for linear calculation mode",
            "properties": {
                "min_power": {
                    "type": "number"
                },
                "max_power": {
                    "type": "number"
                },
                "calibrate": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "fixed_config": {
            "type": "object",
            "description": "Configuration for fixed calculation mode",
            "properties": {
                "power": {
                    "type": "number"
                },
                "states_power": {
                    "type": "object",
                    "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
                    "properties": {
                        "idle": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "playing": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "paused": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "off": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "unavailable": {
                            "type": [
                                "number",
                                "string"
                            ]
                        }
                    },
                    "additionalProperties": {
                        "type": [
                            "number",
                            "string"
                        ]
                    }
                }
            }
        },
        "config_flow_discovery_remarks": {
            "type": "string",
            "description": "Some remarks to show in the GUI config flow on first step of discovery"
        },
        "sensor_config": {
            "type": "object",
            "description": "Sensor configuration options. See the README"
        },
        "sub_profile_select": {
            "type": "object",
            "description": "Configuration to automatically select a sub profile",
            "required": [
                "default",
                "matchers"
            ],
            "properties": {
                "default": {
                    "type": "string",
                    "description": "Default profile to select when non of the matchers apply"
                },
                "matchers": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "enum": [
                                    "attribute",
                                    "entity_id",
                                    "entity_state"
                                ]
                            },
                            "attribute": {
                                "type": "string"
                            },
                            "map": {
                                "type": "object"
                            },
                            "pattern": {
                                "type": "string"
                            },
                            "profile": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "description": "List of matchers which will be checked"
                }
            }
        }
    }
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/signify/LTE002/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Gosuna Smart Plug UP111 (via tuya)",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 2,
        "VERSION": "v0.19.15:docker"
    },
    "name": "Hue White Ambiance E14 w/ BT",
    "standby_power": 0.2,
    "calculation_strategy": "lut",
    "aliases": [
        "9290022944"
    ]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/ikea/LED1805E22EU/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "NOUS A1T with ESPHome 2023.11.6",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v1.9.5:docker"
    },
    "name": "NYMANE PENDANT",
    "standby_power": 0.29
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/arlec/GLD115HA/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "TP-Link Tapo P110",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v0.23.2:docker"
    },
    "name": "Arlec Smart R80 9.5W 806lm CCT Bulb",
    "standby_power": 0.58,
    "calculation_strategy": "lut"
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/ikea/LED2103G5/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script; 6.1 Watts dummy load",
    "measure_device": "Shelly Plus Plug S",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 15,
        "SLEEP_TIME": 3,
        "VERSION": "v1.9.5:docker"
    },
    "name": "TRADFRI bulb E27 WW globe 806lm",
    "standby_power": 0.11,
    "aliases": [
        "TRADFRI bulb E27 WW globe 806lm"
    ]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/tuya/SYS-C24W-CW/model.json
{
  "calculation_strategy": "lut",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Tapo P110",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.9.3:docker"
  },
  "name": "SYLSTAR LED Ceiling Light 24W",
  "standby_power": 0.73,
  "aliases": []
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/lifx/LIFX Z/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Wemo Insight F7C029uk",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 2,
        "VERSION": "v0.17.0:docker"
    },
    "name": "LIFX Z",
    "standby_power": 0.57,
    "calculation_strategy": "lut"
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/innr/RF 263/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured 3 bulbs simultaneously with utils/measure script",
    "measure_device": "Nous A1T",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v1.3.6:docker"
    },
    "name": "RF 263-2 Smart Filament Bulb E27 Vintage (2200K)",
    "standby_power": 0.33
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/genio/I003869/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Tapo P110",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "master"
    },
    "name": "Mirabella Genio Wi-Fi Dimmable 15W ES Par38 LED Bulb",
    "standby_power": 0.51
}
