=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/model_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
    "type": "object",
    "required": [
        "name",
        "standby_power",
        "measure_method",
        "measure_device",
        "calculation_strategy"
    ],
    "properties": {
        "name": {
            "type": "string",
            "description": "The full name"
        },
        "standby_power": {
            "type": "number",
            "minimum": 0.05,
            "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
        },
        "standby_power_on": {
            "type": "number",
            "minimum": 0.05,
            "description": "Power draw when the device is turned on."
        },
        "calculation_strategy": {
            "type": "string",
            "enum": [
                "lut",
                "linear",
                "fixed"
            ],
            "description": "Supported calculation modes"
        },
        "measure_method": {
            "type": "string",
            "enum": [
                "manual",
                "script"
            ],
            "description": "How the device was measured"
        },
        "measure_device": {
            "type": "string",
            "description": "Device which was used to measure"
        },
        "measure_description": {
            "type": "string",
            "description": "Add more information about how you measured the device or any remarks"
        },
        "measure_settings": {
            "type": "object",
            "description": "Settings used for measure script"
        },
        "linked_lut": {
            "type": "string",
            "description": "Use LUT data files from another model"
        },
        "device_type": {
            "type": "string",
            "enum": [
                "light",
                "smart_switch",
                "smart_speaker"
            ],
            "description": "Type of device"
        },
        "calculation_enabled_condition": {
            "type": "string",
            "description": "Template which can be evaluated."
        },
        "aliases": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "Aliases for this model"
        },
        "linear_config": {
            "type": "object",
            "description": "Configuration for linear calculation mode",
            "properties": {
                "min_power": {
                    "type": "number"
                },
                "max_power": {
                    "type": "number"
                },
                "calibrate": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "fixed_config": {
            "type": "object",
            "description": "Configuration for fixed calculation mode",
            "properties": {
                "power": {
                    "type": "number"
                },
                "states_power": {
                    "type": "object",
                    "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
                    "properties": {
                        "idle": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "playing": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "paused": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "off": {
                            "type": [
                                "number",
                                "string"
                            ]
                        },
                        "unavailable": {
                            "type": [
                                "number",
                                "string"
                            ]
                        }
                    },
                    "additionalProperties": {
                        "type": [
                            "number",
                            "string"
                        ]
                    }
                }
            }
        },
        "config_flow_discovery_remarks": {
            "type": "string",
            "description": "Some remarks to show in the GUI config flow on first step of discovery"
        },
        "sensor_config": {
            "type": "object",
            "description": "Sensor configuration options. See the README"
        },
        "sub_profile_select": {
            "type": "object",
            "description": "Configuration to automatically select a sub profile",
            "required": [
                "default",
                "matchers"
            ],
            "properties": {
                "default": {
                    "type": "string",
                    "description": "Default profile to select when non of the matchers apply"
                },
                "matchers": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "enum": [
                                    "attribute",
                                    "entity_id",
                                    "entity_state"
                                ]
                            },
                            "attribute": {
                                "type": "string"
                            },
                            "map": {
                                "type": "object"
                            },
                            "pattern": {
                                "type": "string"
                            },
                            "profile": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "description": "List of matchers which will be checked"
                }
            }
        }
    }
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/yeelight/YLDP06YL/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "TP-Link Kasa KP115",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 10,
        "VERSION": "v0.19.7"
    },
    "name": "Yeelight Smart LED Bulb II Color",
    "standby_power": 1.07,
    "calculation_strategy": "lut",
    "aliases": [
        "color2"
    ]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/signify/LCE002/model.json
{
    "name": "Hue White and Color Ambiance E14 Candle w/ BT",
    "standby_power": 0.28,
    "calculation_strategy": "lut",
    "aliases": [
        "929002294203"
    ],
    "measure_method": "script",
    "measure_device": "AVM FRITZ!DECT 200",
    "measure_description": "Measured with own custom script"
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/ikea/LED2101G4/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly Plug S",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v1.9.2:docker"
    },
    "name": "TRADFRI bulb E12/E14 WS globe 450/470 lumen, dimmable, white spectrum, opal white (LED2101G4)",
    "standby_power": 0.2,
    "aliases": [
        "TRADFRI bulb E14 WS globe 470lm"
    ]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/ikea/LED2201G8/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "TP-Link HS110",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 6,
        "VERSION": "v1.9.11:docker"
    },
    "name": "TR\u00c5DFRI LED bulb E27 1055 lumen, smart wireless dimmable/white spectrum globe",
    "standby_power": 0.19
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/ajax online/AJ_ZIGPROA60/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly 1PM",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 5,
        "VERSION": "v1.0.3:docker"
    },
    "name": "Smart Zigbee pro 12W A60 bulb",
    "standby_power": 0.5,
    "calculation_strategy": "lut"
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/lidl/HG06463A/model.json
{
    "calculation_strategy": "lut",
    "measure_description": "Measured with utils/measure script",
    "measure_device": "TP-Link Tapo P110",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v1.10.0:docker"
    },
    "name": "Livarno Lux E27 ST64 Filament Bulb",
    "standby_power": 0.3
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/signify/LTA001/model.json
{
    "name": "Hue White Ambiance E27",
    "standby_power": 0.29,
    "calculation_strategy": "lut",
    "measure_method": "script",
    "measure_device": "TP-Link Kasa HS110",
    "measure_description": "Measured with script made by smonesi (steps: bri 30/mired 30) and linearly interpolated to provide more data",
    "aliases": [
        "9290022169"
    ]
}

=== klaasnicolaas/Student-homeassistant-config/custom_components/powercalc/data/lidl/HG06462A/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Gosund SP111 with Tasmota",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v0.22.0:docker"
    },
    "name": "Livarno Lux E27 filament bulb",
    "standby_power": 0.2,
    "calculation_strategy": "lut"
}
